services:
  - type: web
    name: salary-prediction-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads
    startCommand: "gunicorn --worker-tmp-dir /dev/shm --workers 2 --threads 4 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
    plan: free
    autoDeploy: true
    healthCheckPath: /status
