services:
  - type: web
    name: salary-prediction-app
    env: python
    buildCommand: "./setup.sh"
    startCommand: "gunicorn --worker-tmp-dir /dev/shm app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    plan: free
